# Generated by Django 2.2.4 on 2019-08-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('city', models.CharField(default='Город не указан', max_length=255, verbose_name='Город')),
                ('phone', models.CharField(default='Номер не указан', max_length=255, verbose_name='Номер телефона')),
                ('email', models.CharField(default='Эдектронная почта не указана', max_length=255, verbose_name='Электронная почта')),
                ('address', models.CharField(default='Адрес не указан', max_length=455, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='TrendyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('rating', models.PositiveIntegerField(default=1, verbose_name='Рейтинг')),
                ('alt', models.CharField(default='Текст по умолчанию', max_length=255, verbose_name='Текст рисунка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Trendy_products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TopSliderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideclass', models.CharField(default='slides slide1', max_length=155, verbose_name='Класс слайда')),
                ('divstyle', models.CharField(default='margin-left:100px', max_length=855, verbose_name='Inline-стиль')),
                ('h3text', models.CharField(default='TRENDING', max_length=255, verbose_name='Большой заголовок типа товаров')),
                ('h2text', models.CharField(default='Product', max_length=255, verbose_name='Название товара')),
                ('ptext', models.CharField(default='Description', max_length=855, verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Slider_products', verbose_name='Картинка товара')),
                ('alt', models.CharField(default='Alt text', max_length=855, verbose_name='Alt текст')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('rating', models.PositiveIntegerField(default=1, verbose_name='Рейтинг')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('rating', models.PositiveIntegerField(default=1, verbose_name='Рейтинг')),
                ('alt', models.CharField(default='Текст по умолчанию', max_length=255, verbose_name='Текст рисунка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HotSliderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideclass', models.CharField(default='slides_hot slide1_hot', max_length=155, verbose_name='Класс слайда')),
                ('divstyle', models.CharField(default='margin: auto', max_length=855, verbose_name='Inline-стиль')),
                ('h3text', models.CharField(default='HOT DEAL', max_length=255, verbose_name='Большой заголовок типа товаров')),
                ('h2text', models.CharField(default='Product', max_length=255, verbose_name='Название товара')),
                ('ptext', models.CharField(default='Description', max_length=855, verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Slider_products', verbose_name='Картинка товара')),
                ('alt', models.CharField(default='Alt text', max_length=855, verbose_name='Alt текст')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('rating', models.PositiveIntegerField(default=1, verbose_name='Рейтинг')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category')),
            ],
        ),
    ]
