# Generated by Django 2.2.4 on 2019-08-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotsliderproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topsliderproduct',
            name='category',
        ),
    ]
