# Generated by Django 2.2.4 on 2019-08-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190830_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsliderproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='topsliderproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category'),
        ),
    ]
