# Generated by Django 2.2.4 on 2019-08-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190830_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isHot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isTopSlider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isTrendy',
            field=models.BooleanField(default=False),
        ),
    ]
