# Generated by Django 2.2.4 on 2019-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190830_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SlideNo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер слайда в карусели'),
        ),
    ]
