# Generated by Django 2.2.4 on 2019-08-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_slideno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopSliderProduct',
        ),
    ]
