# Generated by Django 2.2.4 on 2019-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_topsliderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='Поместить товар в раздел "новое"?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isHot',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isTopSlider',
            field=models.BooleanField(default=False, verbose_name='Товар должен быть в верхнем слайдере?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isTrendy',
            field=models.BooleanField(default=False, verbose_name='Товар сейчас в тренде?'),
        ),
    ]
