# Generated by Django 2.2.4 on 2019-09-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190830_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SlideHotNo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер слайда в карусели "HOT"'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SlideNo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер слайда в карусели верхнего слайдера'),
        ),
        migrations.DeleteModel(
            name='HotSliderProduct',
        ),
    ]
