# Generated by Django 2.2.4 on 2019-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_product_imagehot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageHot',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Картинка должна быть 1366х800 px'),
        ),
    ]
