# Generated by Django 2.2.4 on 2019-08-29 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190828_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='careerCompany',
            field=models.CharField(blank=True, max_length=128, verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 0, 44, 308864, tzinfo=utc)),
        ),
    ]
