# Generated by Django 2.2.4 on 2019-08-29 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190829_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='careerCompany',
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='bdate',
            field=models.DateTimeField(null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 9, 31, 20, 481917, tzinfo=utc)),
        ),
    ]
