# Generated by Django 2.2.4 on 2019-08-29 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190829_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 14, 0, 12, 371725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='bdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
